version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - nodenet

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - nodenet
    volumes:
      #- /usr/src/app/node_modules
      - ./node:/usr/src/app
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
